### ssh-reverse-tunnel deployment file for kubernetes clusters ###
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.codepool.service: reverse-tunnel
  name: reverse-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.codepool.service: reverse-tunnel
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.codepool.service: reverse-tunnel
    spec:
      containers:
        - env:
            - name: TUNNEL_HOST
              value: localhost
            - name: TUNNEL_PORT
              value: "8080"
            - name: REMOTE_HOST
              value: example.org
            - name: REMOTE_PORT
              value: "9001"
            - name: USERNAME
              value: root
            - name: SSH_EXTRA_OPTS
              value: "-v -o ServerAliveInterval=60"
          image: codepool/ssh-reverse-tunnel:v2
          name: reverse-tunnel
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /root/ssh
              name: ssh-key
      restartPolicy: Always
      volumes:
        - name: ssh-key
          hostPath:
            path: /apps/docker/reverse-tunnel/
            type: DirectoryOrCreate
